### PR TITLE
regex readme for cfe resources

### PR DESCRIPTION
**Pull request by lucymonie**

### CODE REVIEW

**Comment by san00** [comment]
Hi Lucymonie,

A good Readme and regex resource that will be useful to others. Some suggestions for minor changes are 
1) changing the start of this sentence from -  Following are lists of tutorial and references...
To - The following is a list of tutorial and references...

2) you might want to add another heading called regex testers or something similar and put the regex101 & regexer links that are currently under the references heading under this section. 
I think it will help make it easier for others to identify and understand what they are.

It  also might be worth checking if there are any other regexe read-me's that you can link to.

I hope this helps :)

**Comment by lucymonie** [comment]
Thanks @san00! Great suggestions. I have incorporated those changes.

**Comment by powderham** [comment]
Hi Lucy, looks good to me. 

How about we add some Katas that are good examples of RegEx in practice? That way people could work towards/past pre-requisites whilst studying this. If you think it is a good idea then I'll ask on gitter.

**Comment by lucymonie** [comment]
That's a great idea @powderham - please do ask on gitter.

**Pull request merged**
